### ISSUE TITLE
check_disk fails with last_me undeclared

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#388]
Using the maint branch I get the following error when running `make`:

```
gcc -DLOCALEDIR=\"/usr/local/nagios/share/locale\" -DHAVE_CONFIG_H -I. -I..  -I.. -I../lib -I../gl -I../intl -I/usr/include  -DNP_VERSION='"2.2.1.git"' -g -O2 -MT check_disk.o -MD -MP -MF .deps/check_disk.Tpo -c -o check_disk.o check_disk.c
check_disk.c: In function ‘main’:
check_disk.c:219:9: error: ‘last_me’ undeclared (first use in this function)
     if (last_me == NULL)
         ^
check_disk.c:219:9: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [check_disk.o] Error 1
make[2]: Leaving directory `/tmp/nagios-plugins/plugins'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/nagios-plugins'
make: *** [all] Error 2
```

@mjtrangoni I see that `last_me` was introduced in https://github.com/nagios-plugins/nagios-plugins/commit/46d9c59b889439b602f73b69594392938e24ee25

**Comment by mjtrangoni** [comment]
@box293 You are right. I noticed it too, and will be fixed with #387.

**Comment by box293** [comment]
Ahh I completely missed that, I looked at all the other check_disk commits and totally missed the first one lol.
